version: '3'
services:
  app:
    image: node:lts-stretch
    volumes:
      - ./cloud-challenge:/app
    ports:
      - 3030:3000
    working_dir: /app/cloud-challenge
    user: 1000:1000
    command: "yarn start"
